language: java
env:
  global:
  - TERM=dumb
jdk:
- openjdk7
install: true
script: "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: ZLZw7eoAalQW5fZIl0oTCLSe40iriYXHnU4OHiZtfMe28De5CUesZfVz6rK5ME4HgzfzIsBVKUeYBZEojVSBE16VN6M+0reWROjtEqmcXqQobjxeGBW/tw8JnDRZU4w9BoG5664rIuAk/eJxT0+Ak0HBxXUH37u0RCyScqFnBYY=
  buildpack: https://github.com/kr/heroku-buildpack-inline
  app: github-activity-poster
  on:
    repo: davidmc24/github-activity-poster
